### ISSUE TITLE
Large Memory Leak

### ISSUE THREAD

**Issue by Zsashas** [MrDimkasStudio/ThaumcraftAdditions#16]
This is in 1.7.10, the console keeps printing this:

[08:08:39] [Client thread/ERROR]: Detected ongoing potential memory leak. 3500 packets have leaked. Top offenders
[08:08:39] [Client thread/ERROR]: 	 thaumicadditions-playnet : 3498

Also, F3 shows some Aura Thread thing, what is this and why is it constantly eating memory?

**Comment by MrDimkasStudio** [comment]
This is currently bugged, but I will no longer work on 1.7.10.

**Comment by Zsashas** [comment]
Isn't this a rather major problem, though?

**Comment by Eufranio** [comment]
He is not caring for 1.7.10 anymore :( I like this mod but its very bugged

**Comment by MrDimkasStudio** [comment]
Hey don't be so upset :) I will continue developing this mod for 1.9 when TC will update ;)

**Comment by Zsashas** [comment]
At least give us a config option to disable this aura-related stuff. It's dragging everything else down with it. Don't leave something with a problem as big as this one.

**Comment by Zsashas** [comment]
The Aura Thread just caused the instance to take 12 minutes to close a single player world...unacceptable.
