### ISSUE TITLE
Dancing Tainted Crops

### ISSUE THREAD

**Issue by Zsashas** [MrDimkasStudio/ThaumcraftAdditions#17]
https://i.gyazo.com/4b8c54956082f45adab4849af3cf53ea.mp4

**Comment by Eufranio** [comment]
MrDimkas should work in 1.7.10 :/

**Comment by MrDimkasStudio** [comment]
Nope, this issue will not be fixed, cause 1.7.10 is no longer supported.
Sorry if I sound like a piece of shit..

**Comment by Zsashas** [comment]
Do Tainted Crops/Seeds/Roots even do anything at this time?

**Comment by MrDimkasStudio** [comment]
Pure aspects.
