### ISSUE TITLE
Crash before loading on v.35

### ISSUE THREAD

**Issue by Zubinator117** [MrDimkasStudio/ThaumcraftAdditions#18]
http://pastebin.com/syKvY2r5

This crash only happens when I have Thaumic Additions installed. I'm playing 1.7.10 and it works with Particle Lib so that's not the problem. I've read something about an mcp folder in the mod not working, but the only configs I see is 1 notepad file. searching mcp doesn't return anything either. Removing Immersive engineering like Enderio asks only goes to a wild goose chase and leads me to uninstall a bunch of mods then telling me to uninstall Thaumic Additions.

**Comment by MrDimkasStudio** [comment]
1) Its Chisel's fault
2) Thaumic Additions will not be supported until Thaumcraft will be out for newest forge-supported minecraft version.

**Comment by Zubinator117** [comment]
Could you explain how it is chisels fault? Chisel and the rest load fine
without Thaumic Additions. Is there anything I can do to make the mods
compatible? Thanks

**Comment by MrDimkasStudio** [comment]
I forgot, that I have AE2 API in the mod, but I will not make any updates. You have to remove ae2 package from jar file of Thaumic Additions.

**Comment by Zubinator117** [comment]
What is the jar file? The actual java mod has a bunch of weird symbols when
I open it

**Comment by MrDimkasStudio** [comment]
It has a different encoding method, but you should be able to open it just like a normal zip file.

**Comment by Zubinator117** [comment]
I'll try that when I get home thanks

**Comment by Zubinator117** [comment]
So... This is a snip of the Jar file. This is the one in the mods folder,
which is what I should be opening is that right?

**Comment by MrDimkasStudio** [comment]
Did you open it with zip-opening app? I guess you just edited it with a text-editing app...

**Comment by Zubinator117** [comment]
Oh... what zip opening app would you recommend?

**Comment by MrDimkasStudio** [comment]
WinRAR

**Comment by Zubinator117** [comment]
I've installed that, but could you tell me what path to take? I tried the
appeng>api>ae2 class file, but deleting that didn't seem to work. Thanks

**Comment by MrDimkasStudio** [comment]
delete whole appeng folder.
