### ISSUE TITLE
Waila crash related

### ISSUE THREAD

**Issue by TsumiHokiro** [MrDimkasStudio/ThaumcraftAdditions#4]
So I've just added Thaumic Additions to a new world and as soon as I look at a block I get a crash from WAILA...
Waila: v.1.5.10_1.7.10
Thaumic Additions: 0.35 for 1.7.10

http://pastebin.com/pcB236kW

**Comment by MrDimkasStudio** [comment]
I guess in 0.36 I should disable WAILA integration... Oh well.. I'll port my desriptors from 1.8 to 1.7.10
