### ISSUE TITLE
Config Option to disable update popup

### ISSUE THREAD

**Issue by Noobsloth** [MrDimkasStudio/ThaumcraftAdditions#5]
The popup is slightly annoying and there's no config option to disable this feature.

**Comment by MrDimkasStudio** [comment]
What's that? What popup do you mean?

**Comment by Noobsloth** [comment]
When the mod is out of date. there is a popup that comes up asking you to update this mod. Can it be removed?

**Comment by MrDimkasStudio** [comment]
If you mean 1.7.10 version, than you can't do that. Otherwise if this is minecraft 1.8.9, download my mod updater,

**Comment by Noobsloth** [comment]
Yes I know that I cant do that. I'm asking can you add in a config to the 1.7.10 version to disable the popup asking players to update.

**Comment by MrDimkasStudio** [comment]
Yes, and, I'll make it so if you install my mod "ModUpdater", it will try to keep TA up to date, without you being noticed.
