### ISSUE TITLE
Thaumic Additions - WAILA conflict. Client crash!

### ISSUE THREAD

**Issue by Antillar** [MrDimkasStudio/ThaumcraftAdditions#8]
When having both mods installed, the client crashes instantly when looking at any block.
Crashlog can be viewed here: http://pastebin.com/rTAjAVjR
Thaumic Additions version 0.35
WAILA version 1.5.10
The reason for the crash lies in ThaumicAdditions mcp folder, which uses an outdated library not supported anymore by WAILA. 
Information given by WAILA owner can be found here: https://bitbucket.org/ProfMobius/waila/issues/134/crash-on-load-with-nosuchfielderror

**Comment by Antillar** [comment]
I have just deleted mcp folder from the mod and it works fine.

**Comment by usafphoenix** [comment]
wish i had found this page 2 hours ago. I spent the last two hours coming to the same conclusion. I also isolated it to the mcp, but there's not much more beyond that that i'm able to help on the manner. Was going to let prof-mobius know, but he's already aware that a few mods are using an outdated api of his. 
:(
i tried to help

**Comment by MrDimkasStudio** [comment]
Seems weird.... I'll have to delete those manually. Though you can't just delete WAILA API from TA by deleting mcp package :P
